from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2000, 1000)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-6, -105,2000, 1100))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\Rio\img\mic.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1300, 800, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(197, 200, 200);\n""")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1550, 800, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(197, 200, 200);\n""")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.label_4 = QtWidgets.QLabel(self.centralwidget)          #Rio text label
        self.label_4.setGeometry(QtCore.QRect(920, 250, 151, 50))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(28)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 201, 51))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("img/8cd3f1898255c045143e1da97fbabf10_w200.gif"))  #line GIF
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(200, 0, 201, 51))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("img/8cd3f1898255c045143e1da97fbabf10_w200.gif"))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(400, 0, 201, 51))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("img/8cd3f1898255c045143e1da97fbabf10_w200.gif"))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(600, 0, 201, 51))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("img/8cd3f1898255c045143e1da97fbabf10_w200.gif"))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(800, 0, 201, 51))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("img/8cd3f1898255c045143e1da97fbabf10_w200.gif"))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(1000, 0, 201, 51))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("img/8cd3f1898255c045143e1da97fbabf10_w200.gif"))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(1200, 0, 201, 51))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("img/8cd3f1898255c045143e1da97fbabf10_w200.gif"))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(1400, 0, 201, 51))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("img/8cd3f1898255c045143e1da97fbabf10_w200.gif"))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(1600, 0, 201, 51))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("img/8cd3f1898255c045143e1da97fbabf10_w200.gif"))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(1800, 0, 201, 51))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("img/8cd3f1898255c045143e1da97fbabf10_w200.gif"))
        self.label_14.setObjectName("label_14")
        
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1352, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Rio"))
        self.pushButton.setText(_translate("MainWindow", "START"))
        self.pushButton_2.setText(_translate("MainWindow", "STOP"))
        self.label_4.setText(_translate("MainWindow", "Hi, I\'m Rio"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
